# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from qtwidgets import Toggle


# Дизайн и элементы главной формы
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 900)
        MainWindow.setMinimumSize(QtCore.QSize(600, 300))
        MainWindow.setMaximumSize(QtCore.QSize(600, 900))
        MainWindow.setBaseSize(QtCore.QSize(600, 900))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/alarmclockIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toggle = Toggle(self)
        self.toggle.resize(60, 35)
        self.toggle.move(540, 70)
        self.toggle.setObjectName("toggle")
        self.label_0 = QtWidgets.QLabel(self.centralwidget)
        self.label_0.setGeometry(QtCore.QRect(410, 0, 580, 20))
        self.label_0.setText("Свернуть в трей:")
        self.label_0.setScaledContents(True)
        self.label_0.setObjectName("label_0")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(135, 72, 425, 80))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(45, 250, 510, 510))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 720, 500, 20))
        self.label_3.setText("Двойной клик на будильник - редактирование!")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 5, 500, 20))
        self.label_4.setText("Список существующих будильников:")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(168, 155, 285, 20))
        self.label_5.setText("")
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.alarmText = QtWidgets.QTextEdit(self.centralwidget)
        self.alarmText.setEnabled(True)
        self.alarmText.setGeometry(QtCore.QRect(10, 310, 561, 71))
        self.alarmText.setObjectName("alarmText")
        self.createAlarm = QtWidgets.QPushButton(self.centralwidget)
        self.createAlarm.setGeometry(QtCore.QRect(200, 720, 171, 31))
        self.createAlarm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createAlarm.setCheckable(False)
        self.createAlarm.setAutoDefault(False)
        self.createAlarm.setDefault(False)
        self.createAlarm.setFlat(False)
        self.createAlarm.setObjectName("CreateAlarm")
        self.hourBox = QtWidgets.QSpinBox(self.centralwidget)
        self.hourBox.setGeometry(QtCore.QRect(30, 270, 61, 31))
        self.hourBox.setMaximum(23)
        self.hourBox.setObjectName("hourBox")
        self.minBox = QtWidgets.QSpinBox(self.centralwidget)
        self.minBox.setGeometry(QtCore.QRect(150, 270, 61, 31))
        self.minBox.setMaximum(59)
        self.minBox.setObjectName("MinBox")
        self.hour_label = QtWidgets.QLabel(self.centralwidget)
        self.hour_label.setGeometry(QtCore.QRect(20, 230, 71, 31))
        self.hour_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour_label.setTextFormat(QtCore.Qt.AutoText)
        self.hour_label.setAlignment(QtCore.Qt.AlignCenter)
        self.hour_label.setObjectName("hour_label")
        self.minut_label = QtWidgets.QLabel(self.centralwidget)
        self.minut_label.setGeometry(QtCore.QRect(120, 220, 131, 51))
        self.minut_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.minut_label.setTextFormat(QtCore.Qt.AutoText)
        self.minut_label.setAlignment(QtCore.Qt.AlignCenter)
        self.minut_label.setObjectName("minut_label")
        self.alarm_list = QtWidgets.QListWidget(self.centralwidget)
        self.alarm_list.setEnabled(True)
        self.alarm_list.setGeometry(QtCore.QRect(10, 30, 581, 681))
        self.alarm_list.setEditTriggers(
            QtWidgets.QAbstractItemView.CurrentChanged |
            QtWidgets.QAbstractItemView.EditKeyPressed |
            QtWidgets.QAbstractItemView.SelectedClicked)
        self.alarm_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.alarm_list.setObjectName("alarm_list")
        self.delete_alarm = QtWidgets.QPushButton(self.centralwidget)
        self.delete_alarm.setGeometry(QtCore.QRect(200, 760, 171, 31))
        self.delete_alarm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_alarm.setCheckable(False)
        self.delete_alarm.setAutoDefault(False)
        self.delete_alarm.setDefault(False)
        self.delete_alarm.setFlat(False)
        self.delete_alarm.setObjectName("delete_alarm")
        self.music_list = QtWidgets.QListWidget(self.centralwidget)
        self.music_list.setGeometry(QtCore.QRect(10, 440, 581, 271))
        self.music_list.setObjectName("music_list")
        self.music_name_label = QtWidgets.QLabel(self.centralwidget)
        self.music_name_label.setGeometry(QtCore.QRect(180, 390, 191, 31))
        self.music_name_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.music_name_label.setTextFormat(QtCore.Qt.AutoText)
        self.music_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.music_name_label.setObjectName("music_name_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(51, 223, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 14, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 216, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 223, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 14, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 216, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 14, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 216, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        self.menubar.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.File = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.File.setFont(font)
        self.File.setObjectName("File")
        self.View = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.View.setFont(font)
        self.View.setObjectName("View")
        self.About = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.About.setFont(font)
        self.About.setObjectName("About")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        font.setPointSize(15)
        self.label_5.setFont(font)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setStyleSheet(
            "color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, "
            "stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), "
            "stop:1 rgba(0, 169, 255, 147));\n")
        self.toolBar.setMovable(False)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/power-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setIconVisibleInMenu(True)
        self.exit.setObjectName("exit")
        self.analog_view = QtWidgets.QAction(MainWindow)
        self.analog_view.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("images/tenor.gif"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.analog_view.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.analog_view.setFont(font)
        self.analog_view.setObjectName("analog_view")
        self.face = QtWidgets.QAction(MainWindow)
        self.face.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/clk_face_num1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("images/clk_face_num2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.face.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.face.setFont(font)
        self.face.setObjectName("analog_view")
        self.number_view = QtWidgets.QAction(MainWindow)
        self.number_view.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/digital-clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("images/dig_clock.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.number_view.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.number_view.setFont(font)
        self.number_view.setObjectName("number_view")
        self.about_program = QtWidgets.QAction(MainWindow)
        self.about_program.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_program.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.about_program.setFont(font)
        self.about_program.setObjectName("about_program")
        self.all_clock = QtWidgets.QAction(MainWindow)
        self.all_clock.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.all_clock.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.all_clock.setFont(font)
        self.all_clock.setObjectName("all_clock")
        self.create_alarmclock = QtWidgets.QAction(MainWindow)
        self.create_alarmclock.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/create_alarmclock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_alarmclock.setIcon(icon6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.create_alarmclock.setFont(font)
        self.create_alarmclock.setObjectName("create_alarmclock")
        self.existing_alarmclock = QtWidgets.QAction(MainWindow)
        self.existing_alarmclock.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/existing_alarmclock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.existing_alarmclock.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.existing_alarmclock.setFont(font)
        self.existing_alarmclock.setObjectName("existing_alarmclock")
        self.File.addAction(self.exit)
        self.View.addAction(self.analog_view)
        self.View.addAction(self.number_view)
        self.View.addAction(self.all_clock)
        self.View.addAction(self.face)
        self.About.addAction(self.about_program)
        self.menu.addAction(self.create_alarmclock)
        self.menu.addAction(self.existing_alarmclock)
        self.menubar.addAction(self.File.menuAction())
        self.menubar.addAction(self.View.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.About.menuAction())
        self.toolBar.addAction(self.exit)
        self.toolBar.addAction(self.analog_view)
        self.toolBar.addAction(self.number_view)
        self.toolBar.addAction(self.all_clock)
        self.toolBar.addAction(self.face)
        self.toolBar.addAction(self.create_alarmclock)
        self.toolBar.addAction(self.existing_alarmclock)
        self.toolBar.addAction(self.about_program)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Будильник"))
        self.alarmText.setDocumentTitle(_translate("MainWindow", "Время"))
        self.alarmText.setPlaceholderText(_translate("MainWindow", "Введите название будильника"))
        self.createAlarm.setText(_translate("MainWindow", "Создать будильник"))
        self.hour_label.setText(_translate("MainWindow", "Часы"))
        self.minut_label.setText(_translate("MainWindow", "Минуты"))
        self.delete_alarm.setText(_translate("MainWindow", "Удалить будильник"))
        self.music_name_label.setText(_translate("MainWindow", "Мелодия будильника:"))
        self.File.setTitle(_translate("MainWindow", "Файл"))
        self.View.setTitle(_translate("MainWindow", "Вид"))
        self.About.setTitle(_translate("MainWindow", "Помощь"))
        self.menu.setTitle(_translate("MainWindow", "Будильник"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.analog_view.setText(_translate("MainWindow", "Аналоговый"))
        self.face.setText(_translate("MainWindow", "Циферблат"))
        self.number_view.setText(_translate("MainWindow", "Цифровой"))
        self.about_program.setText(_translate("MainWindow", "О программе"))
        self.about_program.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.all_clock.setText(_translate("MainWindow", "Общий"))
        self.create_alarmclock.setText(_translate("MainWindow", "Создать"))
        self.existing_alarmclock.setText(_translate("MainWindow", "Посмотреть существующие"))
